### PR TITLE
Fix for security

### PR DESCRIPTION
**Pull request by justice3120**
Fix Arbitrary code execution vulnerabilities
https://jenkins.io/security/advisory/2017-04-10/

### CODE REVIEW

**Comment by justice3120** [comment]
Hi @daniel-beck 
I tried to fix for the SECURITY-494's vulnerability in this PR.
How can this plugin be public again?

**Comment by justice3120** [comment]
Hi @daniel-beck 
Thank you for your reply.
I  added `@RequiredPOST` annotation to the validation method.

**Comment by justice3120** [comment]
Hi @daniel-beck
I released this fix as ver 1.0.2.
I hope this plugin to be public again.
Thanks for your help.

**Comment by daniel-beck** [comment]
@justice3120 Sorry, missed the mentions. I will look into this next week, I hope I will get to it tomorrow. Thanks for acting so quickly!

**Comment by daniel-beck** [comment]
https://github.com/jenkins-infra/backend-update-center2/pull/137

**Pull request merged**
